### ISSUE TITLE
TypeError: currentUser.data(...).currentWorkspace.get is not a function

### ISSUE THREAD

**Issue by ShaunLWM** [antoinedc/hardhat-ethernal#11]
Got notified of this project in hardhat discord so am here to test this out.
After login with `ethernal login`, both the command `ethernal listen` and/or using this library in a hardhat project will throw an error
```
TypeError: currentUser.data(...).currentWorkspace.get is not a function
```
From what I've traced, the data from firestore seemed to return empty value for `currentWorkspace` key
```
{
  apiKey: '<REDACTED>',
  currentWorkspace: ''
} 
```

After poking around a bit, I realized I have to start the hardhat node, then create a workspace in Ethernal web ui and let it listen for transaction before importing this library.

I can create a pull request to throw an helpful error message if no workspace is created if you'd like.

**Comment by antoinedc** [comment]
Hi Shaun,

Indeed the process to get started with Hardhat & create a new workspace is not really obvious. But I hadn't realized it was throwing this error.

A pull request would be amazing yes, if you have some time!

**Comment by ShaunLWM** [comment]
Created a pull request. But feel free to correct me if the syntax is wrong. Haven't touch Firestore for quite some time. Didn't bump the version as well as I think it's your decision. Hope all is good! :)

**Comment by antoinedc** [comment]
Thanks a lot! I'll take a look at this this weekend!
