### ISSUE TITLE
Cannot find module "./Ethernal" (version 0.4.0)

### ISSUE THREAD

**Issue by Jhoscy** [antoinedc/hardhat-ethernal#16]
After installing CLI and hardhat-ethernal, when I tried to run "npx hardhat node" it fails with the error Error: Cannot find module "./Ethernal".
It seems like (with a first check) that there aren't the compiled files in node_modules/hardhat-ethernal/dist so it can't find it with the require in hardhat.config.js.

Trying to install the 0.3.13, the dist folder are filled with all the js.map compiled files and it works as expected.

**Comment by antoinedc** [comment]
Fixed with 0.3.14
