### ISSUE TITLE
import "hardhat-ethernal" breaks hardhat-deploy-ethers

### ISSUE THREAD

**Issue by aspiers** [antoinedc/hardhat-ethernal#19]
This looks very similar to the way that hardhat-waffle can break hardhat-deploy-ethers:

https://github.com/wighawag/hardhat-deploy-ethers/issues/12

I've got a setup which includes the following in my `package.json`:

```
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.3.0-beta.13",
    "hardhat": "^2.9.1",
    "hardhat-deploy": "^0.9.22",
    "hardhat-deploy-ethers": "^0.3.0-beta.12",
    "hardhat-ethernal": "^0.5.0",
```

If `hardhat-ethernal` is not imported in `hardhat.config.ts`, then I see:

```
No need to generate any newer typings.
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> hre.ethers.getContract
[AsyncFunction: getContract]
```

but when I import it, without any other changes, I see:

```
No need to generate any newer typings.
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> hre.ethers.getContract
undefined
```

**Comment by antoinedc** [comment]
Latest update (0.6.0) should fix that!

**Comment by aspiers** [comment]
Yep, seems to have done the job beautifully! :clap: :pray:
