### ISSUE TITLE
Provide ethernal enabler paramenter into hardhat.config.js

### ISSUE THREAD

**Issue by Jhoscy** [antoinedc/hardhat-ethernal#21]
Hi,
I'm working in a team and we faced a problem using Ethernal. Simply, I want to use it, my teammate nope. But in order to work in the same branch, we've made "strange" things into the compiled index.js of the Ethernal (node_modules) to make it works.
As explained in your README we have to set in the hardhat.config.js:

extendEnvironment((hre) => {
    hre.ethernalSync = true;
    hre.ethernalWorkspace = 'Workspace';
    hre.ethernalTrace = false;
    hre.ethernalResetOnStart = 'Hardhat';
});

We had no way to disable the "experimentalAddHardhatNetworkMessageTraceHook" and "extendEnvironment" because there is no check in your module about a simple parameter that you can add in the HardhatUserConfig (please check https://github.com/cgewecke/hardhat-gas-reporter/blob/97258f99e9a7d6bfa1852363e7ba92beb20f64f3/src/type-extensions.ts how this guys have done for the gasReporter).

We've done something like:
interface HardhatUserConfigPlus extends HardhatUserConfig {
  ethernal: boolean;
}
const config: HardhatUserConfigPlus = {
ethernal: true (or false)
...}

and 

config_1.experimentalAddHardhatNetworkMessageTraceHook(async (hre, trace, isMessageTraceFromACall) => {
    if(hre.config.ethernal) {
        hre.ethernal.traceHandler(trace, isMessageTraceFromACall);
    }
});

config_1.extendEnvironment((hre) => {
    if(hre.config.ethernal) {
        //console.log('dafsfeddfas', hre.config.ethernal)
        hre.ethernalSync = hre.ethernalSync !== undefined ? hre.ethernalSync : true;
        hre.ethernalTrace = hre.ethernalTrace !== undefined ? hre.ethernalTrace : true;
        hre.ethernal = plugins_1.lazyObject(() => new Ethernal_1.Ethernal(hre));
    }
});

It would be nice if you'll add it in newer version.
Thanks, nice work!

**Comment by antoinedc** [comment]
Hey!

The fix is to convince your teammate to use Ethernal as well ;)

Just kidding, to be clear what you'd like is a flag that would disable Ethernal entirely without having to turn off each features one by one, correct?

Thanks for the link to the other repo, that looks like a good solution, indeed.

**Comment by Jhoscy** [comment]
Believe me, I've tried for almost two days without convincing him, maybe I need a "seller" course ahaha.

Anyway yes, you can add the support adding the parameter into the hardhat.config.js. 
In this way we can both maintain that import without having compile time error in hardhat, and you can simply disable Ethernal entirely based on that paramenter (expecting a boolean).

We've checked for some solutions and we found the gasReporter that has the exactly (elegant too) behaviour we need.

Stay in touch, again, nice work!

**Comment by antoinedc** [comment]
I released v0.8.1 that adds a global flag. If you update and set `disableEthernal` to true (I did it this way so it's not a breaking change) on the Hardhat config object, this will disable everything (push will return without doing anything as well).

Let me know if that works for  you!

**Comment by Jhoscy** [comment]
Thanks it works!!
