### ISSUE TITLE
Unable to view hardhat-ethernal transactions in https://app.tryethernal.com/

### ISSUE THREAD

**Issue by ianovski** [antoinedc/hardhat-ethernal#25]
Hello,

I am having trouble viewing contracts in the block explorer at https://app.tryethernal.com/ with a premium account.
I have tried using both `hardhat-ethernal` and `ethernal` and observed the following:

#### hardhat.config.ts
In my `hardhat.config.ts` file, I am exporting the following:
```
  ethernal: {
    email: process.env.ETHERNAL_EMAIL,
    password: process.env.ETHERNAL_PASSWORD,
    workspace: <WORKSPACE_NAME>,
    uploadAst: true
  },
```
#### hardhat command
```
hardhat test <path-to-file>
```

#### hardhat logs
I am also seeing the following in my hardhat logs:
```
[Ethernal]  Logged in with <my_email_address>
...
[hardhat tasks]
[Ethernal]  Tracing transaction...
[Ethernal]  Tracing transaction...
[Ethernal]  Tracing transaction...
```

#### app.tryethernal.com Workspace
```
RPC Server: http://127.0.0.1:8545/
Chain: Ethereum
Trace on a hardhat network
```

### Option 2: ethernal
For this option, I am able to view the transactions in the app, however, the `uploadAst` is not working so I cannot interact with the contracts.

#### hardhat.config.ts

```
  ethernal: {
    email: process.env.ETHERNAL_EMAIL,
    password: process.env.ETHERNAL_PASSWORD,
    workspace: <WORKSPACE_NAME>,
    uploadAst: true
  }
```

#### hardhat node
I run a localhost hardhat node using:
```
hardhat node
```

#### ethernal login
```
npx ethernal login
```

#### ethernal listening
```
ethernal listen --astUpload
```

#### hardhat command
```
hardhat --network localhost test <path-to-file>
```
#### app.tryethernal.com Workspace
```
RPC Server: http://127.0.0.1:8545/
Chain: Ethereum
Trace on a hardhat network
```

Thank you in advance for any suggestions.

**Comment by antoinedc** [comment]
Hi!

The uploadAst option is to decode variable storage. Is that what you are looking for? Or are you trying to interact with read/write methods through the UI?

For the latter, you need to call ethernal.push in your deploy script, like this:
```javascript
import { ethernal } from 'hardhat';
await ethernal.push({
  address: contract.address,
  name: contract.name //This needs to exactly match the name of the contract
});
```

**Comment by ianovski** [comment]
Ah, thanks @antoinedc! I misunderstood the purpose of the parameter. I will add the push method to my scripts then.

**Comment by antoinedc** [comment]
Cool! Let me know if that works! Feel free to ping me on Discord (Antoine | Ethernal) otherwise, it might be easier to debug
