### ISSUE TITLE
You are not logged in, please run "ethernal login".

### ISSUE THREAD

**Issue by hmouhtar** [antoinedc/hardhat-ethernal#28]
Even after logging in using `ethernal login`, I get this error. After checking in the source code, seems that the mappings to hardhat's config are not correct.

**Comment by antoinedc** [comment]
Can you try setting your Hardhat config like this? With env variables set up. (you can also hardcode the email/password or put it in other env variables)
```javascript
module.exports = {
    ethernal: {
        email: process.env.ETHERNAL_EMAIL,
        password: process.env.ETHERNAL_PASSWORD
    }
}
```

**Comment by antoinedc** [comment]
Feel free to reopen if you still have the issue.
