### ISSUE TITLE
yarn install fails in github actions

### ISSUE THREAD

**Issue by artdgn** [antoinedc/hardhat-ethernal#3]
When installing the plugin in github actions environment the installation fails with:
```error An unexpected error occurred: "could not find a copy of hardhat to link in /home/runner/work/scaffold-eth/scaffold-eth/node_modules/@scaffold-eth/hardhat/node_modules/hardhat-ethernal/node_modules".```

I'm not experienced with solving dependency issues in JS package managers, so maybe I was doing something wrong but here is the smallest reproducible example:

1. Fork https://github.com/austintgriffith/scaffold-eth which is a framework for creating dapps that uses hardhat. You can find my fork with the example issue here: https://github.com/artdgn/scaffold-eth
2. Add `hardhat-ethernal` to the `packages/hardhat` package: `cd packages/hardhat && yarn add hardhat-ethernal`. Locally it works.
3. Add CI script in `.github/workflows` that will install the packages and run tests or some other task. [Commit and push changes](https://github.com/artdgn/scaffold-eth/commit/bc2ecb0a1c346b16c4bae2e0cf7dd1defbd76455).
4. See the `yarn install` failure: https://github.com/artdgn/scaffold-eth/runs/2536738195

**Comment by antoinedc** [comment]
Hi Arthur,

Thanks for the detailed write-up, I'm able to reproduce it and locally and working on this now! I'll update you as soon as possible.

**Comment by antoinedc** [comment]
Can you try moving hardhat to be a peerDependency? Your package.json should look like this (in packages/hardhat):
```
{
  "name": "@scaffold-eth/hardhat",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "eslint": "^7.5.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-prettier": "^3.1.4"
  },
  "dependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-etherscan": "^2.1.1",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "@openzeppelin/contracts": "^3.2.0",
    "@tenderly/hardhat-tenderly": "^1.0.10",
    "chai": "^4.2.0",
    "chalk": "^4.1.0",
    "ethereum-waffle": "^3.1.1",
    "ethers": "^5.0.17",
    "hardhat-ethernal": "^0.2.3",
    "node-watch": "^0.7.0",
    "qrcode-terminal": "^0.12.0",
    "ramda": "^0.27.1"
  },
  "peerDependencies": {
    "hardhat": "^2.0.11"
  },
  "scripts": {
    "chain": "hardhat node",
    "fork": "hardhat node --fork https://mainnet.infura.io/v3/460f40a260564ac4a4f4b3fffb032dad",
    "test": "hardhat test --network hardhat",
    "compile": "hardhat compile",
    "deploy": "hardhat run scripts/deploy.js",
    "postdeploy": "hardhat run scripts/publish.js",
    "watch": "node scripts/watch.js",
    "accounts": "hardhat accounts",
    "balance": "hardhat balance",
    "send": "hardhat send",
    "generate": "hardhat generate",
    "account": "hardhat account"
  }
}
```

**Comment by artdgn** [comment]
That workaround works, thanks! (`yarn remove hardhat && yarn add hardhat --peer`)
