### ISSUE TITLE
Error when Uploading contract AST

### ISSUE THREAD

**Issue by emretepedev** [antoinedc/hardhat-ethernal#36]
hardhat.config.ts:
```ts
ethernal: {
    uploadAst: true,
    workspace: process.env.ETHERNAL_WORKSPACE || '',
    email: process.env.ETHERNAL_EMAIL || '',
    password: process.env.ETHERNAL_PASSWORD || '',
    resetOnStart: process.env.ETHERNAL_WORKSPACE || '',
  },
```

deploy.ts:
```ts
await ethernal.push({
    name: 'Greeter',
    address: greeter.address,
});
```

Error message:
`[Ethernal]  Uploading contract AST, this might take a while depending on the size of your contract.
[Ethernal]  [FirebaseError: Cannot read properties of undefined (reading 'plan')] {
  code: 'functions/unknown',
  customData: undefined,
  details: undefined
}
[Ethernal]  Uploading dependencies ASTs, this might take a while depending on the size of your contracts.
[Ethernal]  Couldn't sync dependencies: Cannot read properties of undefined (reading 'plan')`

When disabled `uploadAst`, everything works correctly. Any suggestion?

**Comment by antoinedc** [comment]
Hi,

This should be fixed now. Can you give it another try and let me know if that works, please?

**Comment by emretepedev** [comment]
> Hi,
> 
> This should be fixed now. Can you give it another try and let me know if that works, please?

Works well. Thanks!
