### ISSUE TITLE
Cannot find module "../index.js"

### ISSUE THREAD

**Issue by Dan-Nolan** [antoinedc/hardhat-ethernal#7]
After installing `hardhat-ethernal` into a hardhat project and then requiring it in my config, I'm getting the error:

```
Error: Cannot find module '/Users/Dan/Desktop/repos/hardhat-ethernal-test/node_modules/hardhat-ethernal/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
```

Looking in the `node_modules` it doesn't appear to have a `/dist` folder

**Comment by antoinedc** [comment]
Can you try again with version 0.3.2, please? That should fix it!

**Comment by Dan-Nolan** [comment]
Worked like a charm! 🙌
